package main.segment;

public enum SymbolType {
    Base,
    Unknown,
    BaseProcedure,
    BaseData,
        DataColumn,
    Modifier,
        Grouper,
            DCGrouper,
            DtGrouper,
        Filter,
            DVFilter,
            DtFilter,
            FuzzyDtFilter,
            NumFilter,
            LimitFilter,
            ElseFilter,
    Sorter,
    Aggregator,
        Count,
        Sum,
        Mean,
        Stdev,
        Median,
        Maximal,
        Minimal,
    BaseObjective,
        Introduction,
        Generic,
        Comparison,
        Trend,
        Prediction,
        RootCause,
        Proportion,
    Conjunction;
}
